# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170314_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_estimated',
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(to='tasks.Categorias'),
        ),
    ]
