# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20170624_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(to='tasks.Categorias'),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('PUB', 'Publico'), ('PRI', 'Privado')], default='PUB', max_length=3),
        ),
    ]
